repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: local
    hooks:
    -   id: check-changelog
        name: Check for changelog fragment
        entry: python scripts/check_changelog.py
        language: python
        pass_filenames: true
        types: [python, markdown]
        exclude: ^(CHANGELOG\.md|CONTRIBUTING\.md|changelog\.d/.*|\.github/.*|docs/.*|README\.md)$
