name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-changelog:
    name: Check Changelog Fragment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for checking against main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Check for changelog fragment
        id: check-changelog
        run: |
          # Run the check script and capture both exit code and output
          output=$(python scripts/check_changelog.py 2>&1) || true
          echo "::set-output name=check_output::$output"
          if [ $? -ne 0 ]; then
            exit 1
          fi
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR if changelog needed
        if: steps.check-changelog.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **Changelog Entry Required**

            This PR requires a changelog fragment to document the changes. Please either:

            1. Add a changelog fragment file:
              - Location: `changelog.d/icann_reports/` or `changelog.d/shared/`
              - Filename format: `{issue_number}.{type}.md`
              - Types: feat, change, deprecated, removed, fix, security, chore, deps, docs, other

            2. OR include `[skip changelog]` in your commit message if this change doesn't need documentation

            For more details, see our [Release Process](docs/RELEASE_PROCESS.md#2-generate-the-changelog).

            Output from changelog check:
            ```
            ${{ steps.check-changelog.outputs.check_output }}
            ```
          token: ${{ secrets.GITHUB_TOKEN }}
